### ISSUE TITLE
GET finished routes

### ISSUE THREAD

**Issue by sean-heller** [jheller9/todo#1]
https://github.com/jheller9/todo/blob/3985cd171d69fa3da4265ebb4e300f2de8868606/src/main/java/todo/todolist/controller/TodoController.java#L37-L49

this path is a little non-traditional, you would probably do something like GET /todo/finished/{finished} which would be true/false

likewise, is it possible to query this DB by the finished column, rather than getting everything and filtering in code?

**Comment by jason-heller** [comment]
Changed the path to match your recommendation, and swapped to using JPA Specification rather than checking each individual element of a list.
